export const GET_DOGS = 'GET_DOGS';

export const GET_DOGS_BY_BREEDS = 'GET_DOGS_BY_BREEDS';

export const GET_BREED_DETAIL = 'GET_BREED_DETAIL';

export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';

export const ORDER_ALPHABETICALLY_AZ = 'ORDER_ALPHABETICALLY_AZ';

export const ORDER_ALPHABETICALLY_ZA = 'ORDER_ALPHABETICALLY_ZA';

export const FILTER_BY_TEMPERAMENT = 'FILTER_BY_TEMPERAMENT';

export const FILTER_BY_MAX_WEIGHT = 'FILTER_BY_MAX_WEIGHT';

export const FILTER_BY_MIN_WEIGHT = 'FILTER_BY_MIN_WEIGHT';

export const FILTER_BY_BREED_CREATED = 'FILTER_BY_BREED_CREATED';
