export const GET_DOGS = 'GET_DOGS';

export const GET_DOGS_BY_BREEDS = 'GET_DOGS_BY_BREEDS';

export const ORDER_ALPHABETICALLY_AZ = 'ORDER_ALPHABETICALLY_AZ';

export const ORDER_ALPHABETICALLY_ZA = 'ORDER_ALPHABETICALLY_ZA';
